# This playbook should be run on the MASTER node to initialize the cluster
- name: Remove old k8s cluster if existing
  ansible.builtin.command:
    cmd: kubeadm reset --force
  register: kubeadm_reset

- name: Initialize k8s cluster
  ansible.builtin.command:
    cmd: kubeadm init
  register: kubeadm_init
