# This playbook should be run on the MASTER node to initialize the cluster
- name: Remove old k8s cluster if existing
  ansible.builtin.command:
    cmd: kubeadm reset --force
  register: kubeadm_reset

- name: Initialize k8s cluster
  ansible.builtin.command:
    cmd: kubeadm init
  register: kubeadm_init

- name: Create .kube directory
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0755'

- name: Link admin.conf to .kube/config
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf # created by kubeadm init
    path: ~/.kube/config
    state: link

# without this pods can't comunicate between different nodes
- name: Configure Pod Network WeaveNet
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml # TODO: unhardcode it
  register: weavenet_result
