## setup containerd
- name: Insall kernel linux modules
  ansible.builtin.copy:
    src: ./roles/install-k8s/files/k8s.conf # relative from playbook execution
    dest: /etc/modules-load.d/k8s.conf
    mode: "644"

- name: Add overlay module
  community.general.modprobe:
    name: overlay
    state: present

- name: Add br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Configure sysctl params
  ansible.builtin.copy:
    src: ./roles/install-k8s/files/k8s-cri.conf # relative from playbook execution
    dest: /etc/sysctl.d/k8s.conf
    mode: "644"

- name: Load sysctl params
  ansible.builtin.command: sysctl --system

- name: Add apt-key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repo to install containerd
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    # state: present
    update_cache: true

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Create containerd config
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

- name: Change containerd config
  ansible.builtin.command: sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

## setup kubeadm, kubelet and kubectl
- name: Add repo apt-key from k8s
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repo
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install Kubeadm, Kubelet and Kubectl packages
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
