- name: Install docker
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
  ansible.builtin.get_uri:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: 'u+x'
  ansible.builtin.shell: /tmp/get-docker.sh
