- name: Install docker
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
  ansible.builtin.get_uri:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: 'u+x'
  ansible.builtin.shell: /tmp/get-docker.sh

- name: Add repo apt-key from k8s
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repo
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
