- name: Creating Security Group
  #https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_security_group_module.html
  register: basic_firewall
  # amazon.aws.ec2_security_group:
  local_action:
    module: amazon.aws.ec2_security_group
    name: "{{ sec_group_name }}"
    description: sg giropops
    profile: "{{ aws_profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: SSH
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
- name: Creating ec2 instance
  #https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_module.html
  local_action:
    module: amazon.aws.ec2_instance
    security_group: "{{ sec_group_name }}"
    instance_type: "{{ instance_type }}" #t2.micro
    image: "{{ image }}" #ami-0d5eff06f840b45e9
    profile: "{{ aws_profile }}"
    wait: true
    region: "{{ region }}"
    key_name: "{{ key_name }}" #foo.pem
