# https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_security_group_module.html
- name: Creating Security Group
  delegate_to: localhost
  register: basic_firewall
  amazon.aws.ec2_security_group:
    name: "{{ sec_group_name }}"
    description: sg giropops
    profile: "{{ aws_profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: SSH
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_module.html
- name: Creating ec2 instance
  delegate_to: localhost
  register: ec2
  amazon.aws.ec2_security_group:
    security_group: "{{ sec_group_name }}" # sg-xpto
    instance_type: "{{ instance_type }}"   # t2.micro
    image: "{{ image }}"                   # ami-0d5eff06f840b45e9
    profile: "{{ aws_profile }}"
    wait: true
    region: "{{ region }}"                 # us-east-1
    key_name: "{{ key_name }}"             # foo.pem
    count: {{ count }}
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/add_host_module.html
- name: Adding instance to in-memory inventory host group
  with-items: "{{ ec2.instances  }}" # do task for each instance
  ansible.builtin.add_host:
    name: {{ item.public_ip }}
    groups:
      - giropops-new
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
- name: Adding the public IP of the created instance to hosts file
  delegate_to: localhost
  with_items: "{{ ec2.instances }}"  # do task for each instance
  ansible.builtin.lineinfile:
    path: "./hosts.ini"
    regexp: {{ item.public_ip }}
    insertafter: "[kubernetes]"
    line: {{ item.public_ip }}
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
- name: Adding the private IP of the created instance to hosts file
  delegate_to: localhost
  with_items: "{{ ec2.instances }}"  # do task for each instance
  ansible.builtin.lineinfile:
    path: "./hosts.ini"
    regexp: {{ item.private_ip }}
    insertafter: "[kubernetes]"
    line: {{ item.private_ip }}
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_module.html
- name: Waiting for SSH to come up  # pause ansible pipeline until ssh is up
  delegate_to: localhost
  with_items: "{{ ec2.instances }}" 
  ansible.builtin.wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
